name: Java CI with Maven
run-name: ${{ github.actor }} is building a java app 🚀
on: [push]
env: 
  IMAGE_NAME: "spring-maven-app"
  DOCKERHUB_USERNAME: "eric1162004"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install Java 8
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'
      - name: package the app
        run: |
          mvn -B package
          ls -al ${{ github.workspace }}/target
      - name: Upload the jar file
        uses: actions/upload-artifact@v4
        with:
          name: jar-file
          path: target/*.jar
          if-no-files-found: 'error'
          retention-days: 1 day

  dockerize:
    needs: build
    runs-on: ubuntu-latest  
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-file
          path: target
      - name: check the jar file
        run: ls -al ${{ github.workspace }}/target/*.jar
      - name: dockerize the app
        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} .
      - name: Run the container
        run: docker run --rm --name web ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to the registry
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}
      
